trigger:
- master

jobs:

- job: Pipeline
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: 'python3 make.py --input test-results.xml --attachment attachment.txt --output final-results.xml'
    displayName: Run tests

  - script: 'mvn dependency:copy -Dartifact=net.sf.saxon:Saxon-HE:9.9.0-2:jar -DoutputDirectory=.'
    condition: succeededOrFailed()
    displayName: Get saxon utility

  - script: 'java -jar Saxon-HE-9.9.0-2.jar -s:final-results.xml -xsl:junit-to-nunit.xsl -o:nunit-results.xml'
    condition: succeededOrFailed()
    displayName: Convert test results

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'nunit-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
    displayName: Publish test results

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: artifacts
      targetPath: final-results.xml
    displayName: Publish artifacts
